---
id:
name:
lastUpdated:
url:
center: []
bbox:
s2hash:
points:
- id:
  name:
  attributes:
  - key:
    value:
  point:
  - []
lines:
- id:
  name:
  attributes:
  - key:
    value:
  points:
  - []
shapes:
- id:
  name:
  attributes:
  - key:
    value:
  points:
  - []
