---
dataset:
  - id:
    name:
    lastUpdated:
    url:
    center:
      x:
      y:
      z:
    bbox:
    s2hash:  
    points:
    - x:
      y:
      z:
      attributes: 
      - key:
        value:
    lines:
    - id:
      points: 
      - x:
        y:
        z:
        attributes:
        - key:
          value:
    shapes:
    - id: 
      attributes:
      - key:
        value:
      points: 
      - x:
        y:
        z:
