---
project:
  id:
  dem:
    id:
    points:
    - x:
      y:
      z:
  datasets:
  - id:
    center:
      x:
      y:
      z:
    bbox:
    s2hash:  
    points:
    - x:
      y:
      z:
      attributes: 
      - key:
        value:
    lines:
    - id:
      points: 
      - x:
        y:
        z:
        attributes:
        - key:
          value:
    shapes:
    - id: 
      points: 
      - x:
        y:
        z:
        attributes:
        - key:
          value:
